[package]
name = "mdb"
version = "0.1.0"
edition = "2021"

[dependencies]
colored = "2.1.0"
rand = "0.8.5"
serde = {version = "1.0.214", features = ["derive"]}
serenity = "0.12.2"
tokio = {version = "1.41.0", features = ["macros","rt-multi-thread"]}
toml = "0.8.19"
